name: GitHub App installation access token generator
description: Generate an installation access token for a GitHub App that can be for instance used to clone other repositories
inputs:
  private-key:
    description: Private key for the GitHub App
    required: true
  app-id:
    description: GitHub App ID
    required: true
  lifetime-minutes:
    description: JWT lifitime in minutes
    required: false
    default: 10
  repo:
    description: Override GITHUB_REPOSITORY when creating the installation ID
    required: false
outputs:
  token:
    description: Installation access token for the GitHub App
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.private-key }}
    - ${{ inputs.app-id }}
    - ${{ inputs.lifetime-minutes }}
author: Christer Edvartsen <christer.edvartsen@nav.no>
branding:
  icon: unlock
  color: red
